from enum import Enum

class ResourceTypeEnum(Enum):
    COMPARTMENT = "COMPARTMENT"
    CONTAINER = "CONTAINER"
    DRIVER = "DRIVER"
    FERRY = "FERRY"
    FULL_TRAILER = "FULL_TRAILER"
    HANDLING = "HANDLING"
    RIGID = "RIGID"
    SUBCONTRACTOR = "SUBCONTRACTOR"
    TRACTOR = "TRACTOR"
    TRAILER = "TRAILER"
    TRAIN = "TRAIN"
    VAN = "VAN"