from enum import Enum

class UnavailabilityReason(Enum):
    DRIVER_HOLIDAY = "DRIVER_HOLIDAY"
    DRIVER_SICKNESS = "DRIVER_SICKNESS"
    DRIVER_FUNERAL = "DRIVER_FUNERAL"
    DRIVER_OTHER = "DRIVER_OTHER"
    DRIVER_LATE_START_EARLY_LEAVE = "DRIVER_LATE_START_EARLY_LEAVE"
    DRIVER_WORK_ACCIDENT = "DRIVER_WORK_ACCIDENT"
    DRIVER_TEMPORARY_UNEMPLOYMENT = "DRIVER_TEMPORARY_UNEMPLOYMENT"
    VEHICLE_MAINTENANCE = "VEHICLE_MAINTENANCE"
    VEHICLE_REPAIR = "VEHICLE_REPAIR"
    VEHICLE_INSPECTION = "VEHICLE_INSPECTION"
    VEHICLE_CLEANING = "VEHICLE_CLEANING"
    SUBCONTRACTOR_HOLIDAY = "SUBCONTRACTOR_HOLIDAY"
    SUBCONTRACTOR_SICKNESS = "SUBCONTRACTOR_SICKNESS"
    SUBCONTRACTOR_OTHER = "SUBCONTRACTOR_OTHER"