"""
This type stub file was generated by pyright.
"""

from apscheduler.schedulers.blocking import BlockingScheduler

class BackgroundScheduler(BlockingScheduler):
    """
    A scheduler that runs in the background using a separate thread
    (:meth:`~apscheduler.schedulers.base.BaseScheduler.start` will return immediately).

    Extra options:

    ========== =============================================================================
    ``daemon`` Set the ``daemon`` option in the background thread (defaults to ``True``, see
               `the documentation
               <https://docs.python.org/3.4/library/threading.html#thread-objects>`_
               for further details)
    ========== =============================================================================
    """
    _thread = ...
    def start(self, *args, **kwargs): # -> None:
        ...
    
    def shutdown(self, *args, **kwargs): # -> None:
        ...
    


